blueprint:
  name: Camera Timestamp Check
  description: |
    This blueprint will check the timestamp overlays on your security
    cameras and send a notification if the timestamp is not within a specified range
    of the current time. This can help ensure that your camera's time is synchronized
    with your Home Assistant instance. A conversation agent is used to extract the
    timestamp from the camera image overlay. The blueprint supports multiple cameras
    and can notify you via a mobile device or Telegram.
  domain: automation
  source_url: https://github.com/rsiv/home-assistant/blob/main/blueprints/automation/camera-timestamp-check.yaml

  input:
    cameras:
      name: Cameras
      description: One or more cameras to check
      selector:
        entity:
          filter:
            domain: camera
          multiple: true
    trigger_times:
      name: Time
      description: Time of the day to perform the daily timestamp check
      default: "09:00:00"
      selector:
        time: {}
    notify_device:
      name: Mobile device
      description: Select a mobile device to notify. Not used if Telegram notify is set.
      default:
      selector:
        device:
          filter:
            integration: mobile_app
    advanced:
      name: Additional options
      icon: mdi:cog
      description: Additional options
      collapsed: true
      input:            
        max_diff_seconds:
          name: Max time difference
          description: Max allowed difference between camera time and system time
          default: 60
          selector:
            number:
              max: 3600
              min: 0
              unit_of_measurement: seconds
        ai_task:
          name: AI Task
          description: AI task to use for timestamp extraction
          default: ai_task.google_ai_task
          selector:
            entity:
              filter:
                domain: ai_task
        prompt:
          name: Prompt
          description: Prompt to use for timestamp extraction
          default: Extract the timestamp from the overlay in this surveillance camera
            image. The timestamp format is expected to be YYYY-MM-DD HH:MM:SS
            Do not set timezone. Do not include milliseconds.
          selector:
            text:
        telegram_entity:
          name: Telegram notify (Optional)
          description: |
            Entity to send telegram notifications to.
            If set, this will disable notifications to the mobile device set above
          selector:
            entity:
              domain: notify
              integration: telegram_bot
              multiple: false
          default: ""

mode: queued
max: 10

trigger:
  - platform: time
    at: !input trigger_times

variables:
  cameras: !input cameras
  max_diff_seconds: !input max_diff_seconds
  ai_task: !input ai_task
  prompt: !input prompt
  telegram_entity: !input telegram_entity
  notify_telegram: "{{ telegram_entity | length > 0 }}"

action:
  - repeat:
      for_each: "{{ cameras }}"
      sequence:
        - variables:
            camera_entity: "{{ repeat.item }}"
            camera_name: "{{ state_attr(camera_entity, 'friendly_name') }}"
            system_time: "{{ as_timestamp(now()) }}"
        - action: ai_task.generate_data
          data:
            instructions: "{{ prompt }}"
            attachments:
              - media_content_id: "media-source://camera/{{camera_entity}}"
                media_content_type: image/jpeg
            structure:
              timestamp:
                description: >-
                  Overlay timestamp as 19 chars: YYYY-MM-DD HH:MM:SS (no fractions)
                required: true
                selector:
                  text: {}
            entity_id: "{{ ai_task }}"
            task_name: extract timestamp
          response_variable: response
        - variables:
            fixed_timestamp: "{{ response.data.timestamp[:19] }}"
            camera_time: "{{ as_timestamp(fixed_timestamp, default='unknown') }}"
            time_diff: unknown
            message: "{{ camera_name }} camera time unknown: {{ response.data }}"
        - if:
            - condition: template
              value_template: "{{ camera_time != 'unknown' }}"
          then:
            - variables:
                time_diff: "{{ (camera_time - system_time) | round(0, default=1000) }}"
                message: "{{ camera_name }} camera time is off by {{ time_diff }} seconds: {{ fixed_timestamp }}"
        - condition: template
          value_template: "{{ time_diff == 'unknown' or time_diff | abs > max_diff_seconds }}"
        - choose:
          - conditions: "{{ notify_telegram }}"
            sequence:
              - action: telegram_bot.send_message
                data:
                  entity_id: "{{ telegram_entity }}"
                  message: "{{ message }}"
          default:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: Camera timestamp check
            message: "{{ message }}"
